---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty
services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - ansible --version

script:
  - sudo ansible-galaxy install -r tests/requirements.yml
  - sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - docker stop nginx_host || true
  - sudo ansible-playbook  -e 'host_key_checking=False' tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/